spring:
  cloud:
    inetutils:
      use-only-site-local-interfaces: true
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost
server:
  port: 8761
